---
version: '3.4'
services:
  weaviate-auth-okta-cc:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
      - --write-timeout=600s
    image: semitechnologies/weaviate:${WEAVIATE_VERSION}
    ports:
      - 8084:8080
      - 50055:50051
    restart: on-failure:0
    environment:
      AUTHENTICATION_APIKEY_ENABLED: true
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'jane-secret-key,ian-secret-key,jp-secret-key'
      AUTHENTICATION_APIKEY_USERS: 'jane@doe.com,ian-smith,jp-hwang'
      AUTHENTICATION_APIKEY_ROLES: 'viewer,editor,admin'
      PERSISTENCE_DATA_PATH: "./data-weaviate-0"
      BACKUP_FILESYSTEM_PATH: "${PWD}/backups-weaviate-0"
      ENABLE_MODULES: "backup-filesystem"
      CLUSTER_IN_LOCALHOST: true
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      RAFT_BOOTSTRAP_EXPECT: 1
      AUTHORIZATION_ENABLE_RBAC: true
...
